### ISSUE TITLE
Available resources are not handled correctly.

### ISSUE THREAD

**Issue by jimbxb** [pschachte/wybe#228]
Resource availability is not handled correctly throughout the mode checking process.

Example:
```
def foo(?s:string) {
    ?io = phantom
    !read(?s)
}

!println(foo)
```

This program should report that the resource `io` is not available in the call to `read`. However, this compiles fine due to there being a variable named `io` defined, echoing the first line read from stdin.

**Comment by jimbxb** [comment]
The types also do not need to match up. The following program compiles with no errors, executing as above.

```
def foo(?i:int) {
    ?io = "not a phantom"
    !read(?i)
}

!println(foo)
```

**Comment by pschachte** [comment]
The phantom type is now a 0  bit unsigned number, and `phantom` is not a valid value, so the first version of this bug issues this error message:
```
test-cases/final-dump/bug228.wybe:2:11: 'phantom' unknown in foo
```

**Comment by jimbxb** [comment]
Using `?io = 0:phantom` you should still be able to reproduce the issue, unless this has been made illegal

**Comment by pschachte** [comment]
The second test case you provided still compiles, so I'm working on fixing that.  But yes, 0:phantom also compiles.  It should probably be an error to forge a phantom like that, if we can make it an error without breaking manifest constants of number types.

**Comment by jimbxb** [comment]
One way to stop it is to disallow initialisation of 0 bit types, or perhaps specifically `phantom`. 

I'd like a user to, if they wanted, to forge one, however. They'd just be at the mercy of their own sword then.

**Comment by pschachte** [comment]
Fixed in PR #241.

**Comment by jimbxb** [comment]
This bug still persists.

Given this example: 
```
resource foo:int

def use_foo use !foo { pass }

use foo in {
    ?foo = 1
    !use_foo
}
```

I want to have a resource that is uninitialised, and then initialise it within a use block.

This does not compile, with the following error
```
scratch/test.wybe:7:6: Resource test.foo not in scope at call to proc use_foo
```

**Comment by pschachte** [comment]
> What I think we need to do is, if a variable of the correct name is bound, then the corresponding resource should be available

That was the original plan, but it seemed a but messy for variables to magically turn into resources, and it caused problems in implementing the top level main, so I decided to require an explicit `use` to create a scope in which a resource is defined.  But I agree that your example should work, since the explicit `use` should mean that `foo` *is* in scope for the call to `use_foo`.

**Comment by jimbxb** [comment]
There's also the possibility of something like the following:

```
resource foo:int

def use_foo use !foo { pass }

?foo = 1
use foo in {
    !use_foo
}
```

This would "promote" the variable `foo` into a resource in the `use` block, restoring it to a variable after the block.

I'm not sure we want this behaviour, but I could see it's utility.

I'm also unsure on some semantics: does the value of the variable after the use block remain as the same value before the block or the value just before exiting the use block (say if `foo` was modified). I'd lean towards the former, and you can hack your way to get the latter behaviour with the following:

```
?foo = 1
use foo in {
    !use_foo
    ?tmp_foo = foo
}
?foo = tmp_foo
```

**Comment by pschachte** [comment]
Yes, it probably makes more sense to "promote" a variable defined prior to a `use` statement into a resource than to have the `use` statement "shadow" the variable.  In that case, the resource should be "demoted" back to the variable at the end of the use statement, and, to be consistent with the semantics of `use` statements, its value should return to the value before the `use` statement.

**Comment by jimbxb** [comment]
I suppose then the behaviour in this example should be that `foo` is undefined after the `use` block.

```
use foo in {
    ?foo = 1
    !use_foo
}
```

That way it is consistent with the semantics that the value remains unchanged before and after, just that the value happens to be undefined before

**Comment by jimbxb** [comment]
I actually really like this. I was trying to figure out a way to have higher order resourceful terms be illegal outside the context they're defined in. 

i.e I wanted to make something like this illegal
```
use foo in {
    fooer = {resource}{ !use_foo }
}
!fooer
```

All I have to do now is, if I *newly* bind a higher order resourceful term inside a use block, then I consider it unbound after the block. If I rebind a term, then it's okay too, because the old value will still have semantically correct resources.

**Comment by pschachte** [comment]
I thought of another change that may help or hinder.  Resetting a variable to its previous value is just as useful as doing that for a resource, but `use` only works for resources.  So what if we removed that functionality for `use`, and created a new construct that would reset variables at completion of a statement sequence?  So `use` would do nothing other than create a context in which some resource are defined as resources (promoting variables to resources where appropriate, and always demoting the resources to variables at completion of the `use` statment).  We could make it an error or a no-op if it's already defined.  Then we could introduce a new statement:

> `with` *stmt1*,...*stmtn* `{ *stmts* }

which would perform *stmt1* `;` ... *stmtn* `;` *stmts*, and then reset all variables bound by *stmt1*, ... *stmtn* to the values they had prior to the `with` statement (or make them undefined if they were undefined before).

Then you could get the old behaviour by combining `use` and `with`.  How would that interact with HO?

**Comment by jimbxb** [comment]
From my reading of the above are you supposing for a `use` block that all variables defined before should remain with those values? I was thinking it would only reset the values of variables that have been promoted.

As for a `with` statement, I think it would fit in okay from first glance. The issues would still exist from `use` blocks if we got rid of their ability to reset/"undefined" variables

**Comment by jimbxb** [comment]
There's also some type checking issues that have to be resolved here too.

This program compiles, yet probably shouldn't:

```
resource foo:int

def use_foo use ?foo { ?foo = 1 }

?foo = "1.0"
use foo in {
    !use_foo
    !println(foo)
}

!println(foo)
```

Essentially, the resources used in a use block have to have their variables constrained
